
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace terminal {
    using Terminal.Gui;
    
    
    public partial class MyDlg {
        public LoginModel loginModel;
        public MyDlg() {
            InitializeComponent();
            txtUser.SetFocus();
            button.Clicked += () => {
                loginModel = new(){UserName = txtUser.Text.ToString(), Password = txtPass.Text.ToString()};
                RequestStop(this);
                
            };
            
        }
    }
}
