
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace terminal {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyDlg : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label lblUser;
        
        private Terminal.Gui.TextField txtUser;
        
        private Terminal.Gui.Label lblPass;
        
        private Terminal.Gui.TextField txtPass;
        
        private Terminal.Gui.Button button;
        
        private void InitializeComponent() {
            this.button = new Terminal.Gui.Button();
            this.txtPass = new Terminal.Gui.TextField();
            this.lblPass = new Terminal.Gui.Label();
            this.txtUser = new Terminal.Gui.TextField();
            this.lblUser = new Terminal.Gui.Label();
            this.Width = Dim.Percent(50f);
            this.Height = Dim.Percent(50f);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Background = Terminal.Gui.Color.Gray;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Please Log In";
            this.lblUser.Width = 4;
            this.lblUser.Height = 1;
            this.lblUser.X = 13;
            this.lblUser.Y = 3;
            this.lblUser.Visible = true;
            this.lblUser.Data = "lblUser";
            this.lblUser.Text = "Username";
            this.lblUser.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblUser);
            this.txtUser.Width = 20;
            this.txtUser.Height = 1;
            this.txtUser.X = Pos.Right(lblUser) + 2;
            this.txtUser.Y = Pos.Top(lblUser);
            this.txtUser.Visible = true;
            this.txtUser.Secret = false;
            this.txtUser.Data = "txtUser";
            this.txtUser.Text = "";
            this.txtUser.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtUser);
            this.lblPass.Width = 4;
            this.lblPass.Height = 1;
            this.lblPass.X = Pos.Left(lblUser);
            this.lblPass.Y = Pos.Bottom(lblUser) + 2;
            this.lblPass.Visible = true;
            this.lblPass.Data = "lblPass";
            this.lblPass.Text = "Password";
            this.lblPass.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblPass);
            this.txtPass.Width = 20;
            this.txtPass.Height = 1;
            this.txtPass.X = Pos.Right(lblPass) + 2;
            this.txtPass.Y = Pos.Top(lblPass);
            this.txtPass.Visible = true;
            this.txtPass.Secret = true;
            this.txtPass.Data = "txtPass";
            this.txtPass.Text = "";
            this.txtPass.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtPass);
            this.button.Width = 6;
            this.button.Height = 1;
            this.button.X = Pos.Center();
            this.button.Y = Pos.Bottom(lblPass) + 2;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "OK";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = true;
            this.Add(this.button);
        }
    }
}
